/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthProxyController_register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthProxyController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthProxyController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthProxyController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthProxyController_getProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['AuthProxyController_updateProfile'];
    trace?: never;
  };
  '/api/auth/balance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthProxyController_getBalance'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/balance/deposit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthProxyController_deposit'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/balance/reserve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthProxyController_reserve'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/balance/release': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthProxyController_release'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/balance/refund': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthProxyController_refund'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/transactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthProxyController_getTransactions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthProxyController_listUsers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthProxyController_getUserById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/users/{id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['AuthProxyController_updateUserStatus'];
    trace?: never;
  };
  '/api/trainers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TrainingProxyController_getTrainers'];
    put?: never;
    post: operations['TrainingProxyController_createTrainer'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/trainers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TrainingProxyController_getTrainerById'];
    put?: never;
    post?: never;
    delete: operations['TrainingProxyController_deleteTrainer'];
    options?: never;
    head?: never;
    patch: operations['TrainingProxyController_updateTrainer'];
    trace?: never;
  };
  '/api/trainings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TrainingProxyController_getTrainings'];
    put?: never;
    post: operations['TrainingProxyController_createTraining'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/trainings/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TrainingProxyController_getTrainingById'];
    put?: never;
    post?: never;
    delete: operations['TrainingProxyController_deleteTraining'];
    options?: never;
    head?: never;
    patch: operations['TrainingProxyController_updateTraining'];
    trace?: never;
  };
  '/api/schedule': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TrainingProxyController_getSchedule'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedule/trainer/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TrainingProxyController_getTrainerSchedule'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bookings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['BookingProxyController_getBookings'];
    put?: never;
    post: operations['BookingProxyController_createBooking'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bookings/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['BookingProxyController_getBookingById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bookings/{id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['BookingProxyController_cancelBooking'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/waitlist': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['BookingProxyController_getWaitlist'];
    put?: never;
    post: operations['BookingProxyController_joinWaitlist'];
    delete: operations['BookingProxyController_leaveWaitlist'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/waitlist/position': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['BookingProxyController_getWaitlistPosition'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bookings/training/{trainingId}/count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['BookingProxyController_getTrainingBookingCount'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bookings/training/{trainingId}/participants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['BookingProxyController_getTrainingParticipants'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['NotificationProxyController_getNotifications'];
    put?: never;
    post?: never;
    delete: operations['NotificationProxyController_deleteAllNotifications'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/notifications/unread-count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['NotificationProxyController_getUnreadCount'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/notifications/{id}/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['NotificationProxyController_markAsRead'];
    trace?: never;
  };
  '/api/notifications/read-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['NotificationProxyController_markAllAsRead'];
    trace?: never;
  };
  '/api/notifications/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['NotificationProxyController_deleteNotification'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterDto: {
      /** @example user@example.com */
      email: string;
      /** @example password123 */
      password: string;
      /** @example John Doe */
      name: string;
      /** @example +1234567890 */
      phone?: string;
      /** @example 1990-01-01 */
      birthDate?: string;
      /** @enum {string} */
      gender?: 'male' | 'female';
    };
    UserResponseDto: {
      id: string;
      email: string;
      name: string;
      phone?: string;
      birthDate?: string;
      /** @enum {string} */
      gender?: 'male' | 'female';
      /** @enum {string} */
      role: 'client' | 'admin';
      balance: number;
      /** @enum {string} */
      status: 'active' | 'blocked';
      createdAt: string;
    };
    RegisterResponseBody: {
      accessToken: string;
      user: components['schemas']['UserResponseDto'];
    };
    LoginDto: {
      /** @example user@example.com */
      email: string;
      /** @example password123 */
      password: string;
    };
    LoginResponseBody: {
      /** @example jwt-access-token */
      accessToken: string;
    };
    LogoutResponseBody: {
      /** @example Logged out successfully */
      message: string;
    };
    UserProfileDto: {
      id: string;
      email: string;
      name: string;
      phone?: string;
      birthDate?: string;
      /** @enum {string} */
      gender?: 'male' | 'female';
      /** @enum {string} */
      role: 'client' | 'admin';
      balance: number;
      /** @enum {string} */
      status: 'active' | 'blocked';
      createdAt: string;
      updatedAt: string;
    };
    UpdateUserDto: {
      /** @example John Doe */
      name?: string;
      /** @example +1234567890 */
      phone?: string;
      /** @example 1990-01-01 */
      birthDate?: string;
      /** @enum {string} */
      gender?: 'male' | 'female';
    };
    BalanceResponseDto: {
      /** @example 1500 */
      balance: number;
    };
    UpdateBalanceDto: {
      /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
      userId: string;
      /** @example 100 */
      amount: number;
      /** @example Deposit for training */
      description?: string;
    };
    TransactionResponseDto: {
      id: string;
      /** @enum {string} */
      type: 'deposit' | 'withdraw' | 'refund' | 'reserve' | 'release';
      amount: number;
      bookingId?: Record<string, never>;
      description?: Record<string, never>;
      createdAt: string;
    };
    TransactionListResponseDto: {
      items: components['schemas']['TransactionResponseDto'][];
      /** @example 25 */
      total: number;
      /** @example 1 */
      page: number;
      /** @example 10 */
      limit: number;
    };
    UserDto: {
      id: string;
      email: string;
      name: string;
      phone?: string;
      birthDate?: string;
      /** @enum {string} */
      gender?: 'male' | 'female';
      /** @enum {string} */
      role: 'client' | 'admin';
      balance: number;
      /** @enum {string} */
      status: 'active' | 'blocked';
      createdAt: string;
    };
    UserListResponseDto: {
      items: components['schemas']['UserDto'][];
      /** @example 25 */
      total: number;
      /** @example 1 */
      page: number;
      /** @example 10 */
      limit: number;
    };
    UpdateUserStatusDto: {
      /** @enum {string} */
      status: 'active' | 'blocked';
    };
    TrainerResponseDto: {
      id: string;
      name: string;
      bio?: Record<string, never>;
      avatarUrl?: Record<string, never>;
      isActive: boolean;
      createdAt: string;
      updatedAt: string;
    };
    CreateTrainerDto: {
      /** @example John Smith */
      name: string;
      /** @example Experienced fitness trainer */
      bio?: string;
      /** @example https://example.com/avatar.jpg */
      avatarUrl?: string;
    };
    UpdateTrainerDto: {
      /** @example John Smith */
      name?: string;
      /** @example Experienced fitness trainer */
      bio?: string;
      /** @example https://example.com/avatar.jpg */
      avatarUrl?: string;
      isActive?: boolean;
    };
    TrainingResponseDto: {
      id: string;
      title: string;
      description?: Record<string, never>;
      /** @enum {string} */
      type:
        | 'yoga'
        | 'pilates'
        | 'crossfit'
        | 'boxing'
        | 'strength'
        | 'cardio'
        | 'dance'
        | 'stretching';
      trainerId: string;
      trainerName?: string;
      scheduledAt: string;
      durationMinutes: number;
      capacity: number;
      currentParticipants: number;
      availableSlots: number;
      /** @description Number of users on the waitlist */
      waitlistCount: number;
      price: number;
      /** @enum {string} */
      status: 'scheduled' | 'cancelled' | 'completed';
      createdAt: string;
      updatedAt: string;
    };
    TrainingListResponseDto: {
      items: components['schemas']['TrainingResponseDto'][];
      /** @example 25 */
      count: number;
    };
    CreateTrainingDto: {
      /** @example Morning Yoga */
      title: string;
      /** @example A relaxing yoga session */
      description?: string;
      /** @enum {string} */
      type:
        | 'yoga'
        | 'pilates'
        | 'crossfit'
        | 'boxing'
        | 'strength'
        | 'cardio'
        | 'dance'
        | 'stretching';
      /** @example 550e8400-e29b-41d4-a716-446655440000 */
      trainerId: string;
      /** @example 2024-01-15T10:00:00Z */
      scheduledAt: string;
      /** @example 60 */
      durationMinutes: number;
      /** @example 20 */
      capacity: number;
      /** @example 500 */
      price: number;
    };
    UpdateTrainingDto: {
      /** @example Morning Yoga */
      title?: string;
      /** @example A relaxing yoga session */
      description?: string;
      /** @enum {string} */
      type?:
        | 'yoga'
        | 'pilates'
        | 'crossfit'
        | 'boxing'
        | 'strength'
        | 'cardio'
        | 'dance'
        | 'stretching';
      /** @example 550e8400-e29b-41d4-a716-446655440000 */
      trainerId?: string;
      /** @example 2024-01-15T10:00:00Z */
      scheduledAt?: string;
      /** @example 60 */
      durationMinutes?: number;
      /** @example 20 */
      capacity?: number;
      /** @example 500 */
      price?: number;
      /** @enum {string} */
      status?: 'scheduled' | 'cancelled' | 'completed';
    };
    ScheduleTrainingDto: {
      id: string;
      title: string;
      type: string;
      scheduledAt: string;
      durationMinutes: number;
    };
    WeekScheduleDayDto: {
      date: string;
      trainings: components['schemas']['ScheduleTrainingDto'][];
    };
    WeekScheduleResponseDto: {
      weekStart: string;
      weekEnd: string;
      days: components['schemas']['WeekScheduleDayDto'][];
    };
    TrainerScheduleResponseDto: {
      trainer: Record<string, never>;
      trainings: components['schemas']['ScheduleTrainingDto'][];
    };
    BookingResponseDto: {
      /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
      id: string;
      /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
      userId: string;
      /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
      trainingId: string;
      /** @enum {string} */
      status: 'confirmed' | 'cancelled';
      /** @example 2024-01-15T10:00:00Z */
      createdAt: string;
      /** @example 2024-01-15T10:00:00Z */
      updatedAt: string;
    };
    BookingListResponseDto: {
      items: components['schemas']['BookingResponseDto'][];
      /** @example 25 */
      total: number;
      /** @example 1 */
      page: number;
      /** @example 10 */
      limit: number;
    };
    BookingDto: {
      id: string;
      trainingId: string;
      userId: string;
      /** @enum {string} */
      status: 'confirmed' | 'cancelled' | 'completed';
      /** Format: date-time */
      bookedAt: string;
      /** Format: date-time */
      cancelledAt?: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateBookingDto: {
      /** @example 550e8400-e29b-41d4-a716-446655440000 */
      trainingId: string;
    };
    CancelBookingDto: {
      /** @example Unable to attend */
      reason?: string;
    };
    WaitlistResponseDto: {
      /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
      id: string;
      /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
      userId: string;
      /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
      trainingId: string;
      /** @example 3 */
      position: number;
      /** @example 2024-01-15T10:00:00Z */
      joinedAt: string;
    };
    WaitlistDto: {
      id: string;
      trainingId: string;
      userId: string;
      position: number;
      /** Format: date-time */
      joinedAt: string;
    };
    TrainingBookingCountDto: {
      /** @example 5 */
      confirmedCount: number;
      /** @example 2 */
      waitlistCount: number;
    };
    JoinWaitlistDto: {
      /** @example 550e8400-e29b-41d4-a716-446655440000 */
      trainingId: string;
    };
    NotificationResponseDto: {
      /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
      id: string;
      /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
      userId: string;
      /** @enum {string} */
      type:
        | 'booking_confirmation'
        | 'booking_cancellation'
        | 'balance_change'
        | 'training_reminder'
        | 'waitlist_joined'
        | 'waitlist_promoted';
      /** @example Training Reminder */
      title: string;
      /** @example Your training starts in 30 minutes */
      content: string;
      /** @example false */
      isRead: boolean;
      /**
       * Format: date-time
       * @example 2024-01-15T10:00:00Z
       */
      createdAt: string;
    };
    NotificationListResponseDto: {
      items: components['schemas']['NotificationResponseDto'][];
      /** @example 25 */
      total: number;
      /** @example 1 */
      page: number;
      /** @example 10 */
      limit: number;
    };
    UnreadCountResponseDto: {
      /** @example 5 */
      count: number;
    };
    NotificationDto: {
      id: string;
      userId: string;
      /** @enum {string} */
      type:
        | 'booking_confirmation'
        | 'booking_cancellation'
        | 'balance_change'
        | 'training_reminder'
        | 'waitlist_joined'
        | 'waitlist_promoted';
      title: string;
      content: string;
      isRead: boolean;
      metadata?: Record<string, never>;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      readAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthProxyController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterDto'];
      };
    };
    responses: {
      /** @description Registration successful */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RegisterResponseBody'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      /** @description Login successful */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResponseBody'];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token refreshed successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResponseBody'];
        };
      };
      /** @description Invalid refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logout successful */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LogoutResponseBody'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_getProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User profile retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserProfileDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserDto'];
      };
    };
    responses: {
      /** @description Profile updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserProfileDto'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_getBalance: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Balance retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BalanceResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_deposit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateBalanceDto'];
      };
    };
    responses: {
      /** @description Deposit successful */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionResponseDto'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_reserve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateBalanceDto'];
      };
    };
    responses: {
      /** @description Funds reserved successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionResponseDto'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient balance */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_release: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateBalanceDto'];
      };
    };
    responses: {
      /** @description Funds released successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionResponseDto'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_refund: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateBalanceDto'];
      };
    };
    responses: {
      /** @description Refund processed successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionResponseDto'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_getTransactions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Transactions retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionListResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_listUsers: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        status?: 'active' | 'blocked';
        role?: 'client' | 'admin';
        ids?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List all users (admin only) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserListResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_getUserById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get user details by ID (admin only) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthProxyController_updateUserStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserStatusDto'];
      };
    };
    responses: {
      /** @description Block/unblock user (admin only) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_getTrainers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trainers retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrainerResponseDto'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_createTrainer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTrainerDto'];
      };
    };
    responses: {
      /** @description Trainer created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrainerResponseDto'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_getTrainerById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trainer retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrainerResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Trainer not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_deleteTrainer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trainer deactivated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Trainer not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_updateTrainer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTrainerDto'];
      };
    };
    responses: {
      /** @description Trainer updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrainerResponseDto'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Trainer not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_getTrainings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trainings retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrainingListResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_createTraining: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTrainingDto'];
      };
    };
    responses: {
      /** @description Training created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrainingResponseDto'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_getTrainingById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Training retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrainingResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Training not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_deleteTraining: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Training cancelled */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Training not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_updateTraining: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTrainingDto'];
      };
    };
    responses: {
      /** @description Training updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrainingResponseDto'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - Admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Training not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_getSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Weekly schedule retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WeekScheduleResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrainingProxyController_getTrainerSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trainer schedule retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrainerScheduleResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BookingProxyController_getBookings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bookings retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookingListResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BookingProxyController_createBooking: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateBookingDto'];
      };
    };
    responses: {
      /** @description Booking created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookingDto'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Training not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Booking already exists or no available slots */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BookingProxyController_getBookingById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Booking retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookingDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Booking not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BookingProxyController_cancelBooking: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CancelBookingDto'];
      };
    };
    responses: {
      /** @description Booking cancelled */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookingDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Booking not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Booking already cancelled or past training */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BookingProxyController_getWaitlist: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Waitlist retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WaitlistResponseDto'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BookingProxyController_joinWaitlist: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JoinWaitlistDto'];
      };
    };
    responses: {
      /** @description Added to waitlist */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WaitlistDto'];
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Training not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Already on waitlist or has active booking */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BookingProxyController_leaveWaitlist: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Left waitlist */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Removed from waitlist */
            message?: string;
          };
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not on waitlist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BookingProxyController_getWaitlistPosition: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Waitlist position retrieved. Position -1 indicates user is not on the waitlist. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WaitlistDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BookingProxyController_getTrainingBookingCount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trainingId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Booking count for training retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrainingBookingCountDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BookingProxyController_getTrainingParticipants: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trainingId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Training participants retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationProxyController_getNotifications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notifications retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationListResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationProxyController_deleteAllNotifications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All notifications deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            deleted?: number;
          };
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationProxyController_getUnreadCount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Unread count retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UnreadCountResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationProxyController_markAsRead: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notification marked as read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Notification not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationProxyController_markAllAsRead: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All notifications marked as read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            updated?: number;
          };
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationProxyController_deleteNotification: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notification deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            deleted?: boolean;
          };
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Notification not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
