/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PaymentResultRouteImport } from './routes/payment.result'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrainersRouteImport } from './routes/admin.trainers'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as ClientScheduleRouteImport } from './routes/_client.schedule'
import { Route as ClientProfileRouteImport } from './routes/_client.profile'
import { Route as ClientNotificationsRouteImport } from './routes/_client.notifications'
import { Route as ClientHistoryRouteImport } from './routes/_client.history'
import { Route as ClientDashboardRouteImport } from './routes/_client.dashboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminScheduleIndexRouteImport } from './routes/admin.schedule.index'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminScheduleNewRouteImport } from './routes/admin.schedule.new'
import { Route as ClientBookingIdRouteImport } from './routes/_client.booking.$id'
import { Route as AdminScheduleEditIdRouteImport } from './routes/admin.schedule.edit.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment/result',
  path: '/payment/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainersRoute = AdminTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const ClientScheduleRoute = ClientScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRoute,
} as any)
const ClientHistoryRoute = ClientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminScheduleIndexRoute = AdminScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminScheduleRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminScheduleNewRoute = AdminScheduleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminScheduleRoute,
} as any)
const ClientBookingIdRoute = ClientBookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => ClientRoute,
} as any)
const AdminScheduleEditIdRoute = AdminScheduleEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminScheduleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof ClientDashboardRoute
  '/history': typeof ClientHistoryRoute
  '/notifications': typeof ClientNotificationsRoute
  '/profile': typeof ClientProfileRoute
  '/schedule': typeof ClientScheduleRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRouteWithChildren
  '/admin/trainers': typeof AdminTrainersRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/payment/result': typeof PaymentResultRoute
  '/admin/': typeof AdminIndexRoute
  '/booking/$id': typeof ClientBookingIdRoute
  '/admin/schedule/new': typeof AdminScheduleNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/schedule/': typeof AdminScheduleIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/schedule/edit/$id': typeof AdminScheduleEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof ClientDashboardRoute
  '/history': typeof ClientHistoryRoute
  '/notifications': typeof ClientNotificationsRoute
  '/profile': typeof ClientProfileRoute
  '/schedule': typeof ClientScheduleRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/payment/result': typeof PaymentResultRoute
  '/admin': typeof AdminIndexRoute
  '/booking/$id': typeof ClientBookingIdRoute
  '/admin/schedule/new': typeof AdminScheduleNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/schedule': typeof AdminScheduleIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/schedule/edit/$id': typeof AdminScheduleEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_client': typeof ClientRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_client/dashboard': typeof ClientDashboardRoute
  '/_client/history': typeof ClientHistoryRoute
  '/_client/notifications': typeof ClientNotificationsRoute
  '/_client/profile': typeof ClientProfileRoute
  '/_client/schedule': typeof ClientScheduleRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRouteWithChildren
  '/admin/trainers': typeof AdminTrainersRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/payment/result': typeof PaymentResultRoute
  '/admin/': typeof AdminIndexRoute
  '/_client/booking/$id': typeof ClientBookingIdRoute
  '/admin/schedule/new': typeof AdminScheduleNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/schedule/': typeof AdminScheduleIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/schedule/edit/$id': typeof AdminScheduleEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/unauthorized'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/schedule'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/trainers'
    | '/admin/users'
    | '/payment/result'
    | '/admin/'
    | '/booking/$id'
    | '/admin/schedule/new'
    | '/admin/users/$id'
    | '/admin/schedule/'
    | '/admin/users/'
    | '/admin/schedule/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/schedule'
    | '/admin/reports'
    | '/admin/trainers'
    | '/payment/result'
    | '/admin'
    | '/booking/$id'
    | '/admin/schedule/new'
    | '/admin/users/$id'
    | '/admin/schedule'
    | '/admin/users'
    | '/admin/schedule/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_client'
    | '/admin'
    | '/unauthorized'
    | '/_auth/login'
    | '/_auth/register'
    | '/_client/dashboard'
    | '/_client/history'
    | '/_client/notifications'
    | '/_client/profile'
    | '/_client/schedule'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/trainers'
    | '/admin/users'
    | '/payment/result'
    | '/admin/'
    | '/_client/booking/$id'
    | '/admin/schedule/new'
    | '/admin/users/$id'
    | '/admin/schedule/'
    | '/admin/users/'
    | '/admin/schedule/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  PaymentResultRoute: typeof PaymentResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/payment/result': {
      id: '/payment/result'
      path: '/payment/result'
      fullPath: '/payment/result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trainers': {
      id: '/admin/trainers'
      path: '/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AdminTrainersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_client/schedule': {
      id: '/_client/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ClientScheduleRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/profile': {
      id: '/_client/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/notifications': {
      id: '/_client/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/history': {
      id: '/_client/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ClientHistoryRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/dashboard': {
      id: '/_client/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/schedule/': {
      id: '/admin/schedule/'
      path: '/'
      fullPath: '/admin/schedule/'
      preLoaderRoute: typeof AdminScheduleIndexRouteImport
      parentRoute: typeof AdminScheduleRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/schedule/new': {
      id: '/admin/schedule/new'
      path: '/new'
      fullPath: '/admin/schedule/new'
      preLoaderRoute: typeof AdminScheduleNewRouteImport
      parentRoute: typeof AdminScheduleRoute
    }
    '/_client/booking/$id': {
      id: '/_client/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof ClientBookingIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/schedule/edit/$id': {
      id: '/admin/schedule/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/schedule/edit/$id'
      preLoaderRoute: typeof AdminScheduleEditIdRouteImport
      parentRoute: typeof AdminScheduleRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ClientRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientHistoryRoute: typeof ClientHistoryRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientScheduleRoute: typeof ClientScheduleRoute
  ClientBookingIdRoute: typeof ClientBookingIdRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDashboardRoute: ClientDashboardRoute,
  ClientHistoryRoute: ClientHistoryRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientScheduleRoute: ClientScheduleRoute,
  ClientBookingIdRoute: ClientBookingIdRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface AdminScheduleRouteChildren {
  AdminScheduleNewRoute: typeof AdminScheduleNewRoute
  AdminScheduleIndexRoute: typeof AdminScheduleIndexRoute
  AdminScheduleEditIdRoute: typeof AdminScheduleEditIdRoute
}

const AdminScheduleRouteChildren: AdminScheduleRouteChildren = {
  AdminScheduleNewRoute: AdminScheduleNewRoute,
  AdminScheduleIndexRoute: AdminScheduleIndexRoute,
  AdminScheduleEditIdRoute: AdminScheduleEditIdRoute,
}

const AdminScheduleRouteWithChildren = AdminScheduleRoute._addFileChildren(
  AdminScheduleRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScheduleRoute: typeof AdminScheduleRouteWithChildren
  AdminTrainersRoute: typeof AdminTrainersRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReportsRoute: AdminReportsRoute,
  AdminScheduleRoute: AdminScheduleRouteWithChildren,
  AdminTrainersRoute: AdminTrainersRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  PaymentResultRoute: PaymentResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
